Set Shell zsh

Output demo.gif

Set FontSize 15
Set Width 600
Set Height 400
Set Padding 15
Set WindowBar Colorful
Set Theme "nord"
Require lpx

Hide

Type@10ms lpx earth.gif
Enter
Sleep 1s

Show

Sleep 500ms

Space
Sleep 5s
Space

Sleep 500ms

Type "4"
Sleep 500ms

Type "["
Sleep 500ms

Type@300ms "LL]"
Sleep 500ms

Space
Sleep 1s
Type@500ms "kkk"
Sleep 1s

Space
Sleep 500ms

Type "C"
Sleep 500ms

Type@500ms "HHH"
Sleep 1s
