Set Shell zsh

Output speed.gif

Set FontSize 15
Set Width 500
Set Height 400
Set Padding 15
Set WindowBar Colorful
Set Theme "nord"
Require lpx

Hide

Type@10ms lpx earth.gif
Enter
Sleep 1s

Show

Sleep 500ms

Space

Sleep 2s
Type "k"
Sleep 1s
Type "k"
Sleep 1s
Type "k"
Sleep 1s
Type "k"
Sleep 1s
Type "j"
Sleep 500ms
Type "j"
Sleep 500ms
Type "j"
Sleep 500ms
Type "j"
Sleep 1s
Type "j"
Sleep 3s
Type "j"
Sleep 2s

Space
